# Generated by Django 5.2.6 on 2025-09-16 01:55

import LevelUp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LevelUp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[LevelUp.validators.validar_formato_rut]),
        ),
    ]
