# Generated by Django 5.2.6 on 2025-10-05 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LevelUp', '0003_actividad_docente_actividad_es_publicada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('codigo', models.SlugField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(choices=[(4, '4° Básico'), (5, '5° Básico')])),
                ('letra', models.CharField(default='A', max_length=2)),
            ],
            options={
                'ordering': ['nivel', 'letra'],
                'unique_together': {('nivel', 'letra')},
            },
        ),
        migrations.CreateModel(
            name='GrupoRefuerzoNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(choices=[(4, '4° Básico'), (5, '5° Básico')], unique=True)),
                ('capacidad_sugerida', models.PositiveIntegerField(default=10)),
                ('profesor_ingles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_refuerzo_ing', to=settings.AUTH_USER_MODEL)),
                ('profesor_matematicas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_refuerzo_mate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nivel'],
            },
        ),
        migrations.CreateModel(
            name='GrupoRefuerzoNivelAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LevelUp.asignatura')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LevelUp.gruporefuerzonivel')),
            ],
            options={
                'unique_together': {('grupo', 'alumno')},
            },
        ),
        migrations.AddField(
            model_name='gruporefuerzonivel',
            name='alumnos',
            field=models.ManyToManyField(related_name='grupos_refuerzo_nivel', through='LevelUp.GrupoRefuerzoNivelAlumno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PerfilAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('dificultad_matematicas', models.BooleanField(default=False)),
                ('dificultad_ingles', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_alumno', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_docente', to=settings.AUTH_USER_MODEL)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='LevelUp.asignatura')),
            ],
            options={
                'unique_together': {('profesor', 'asignatura')},
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='LevelUp.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('estudiante', 'curso')},
            },
        ),
    ]
