# Generated by Django 5.2.6 on 2025-10-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LevelUp', '0004_asignatura_curso_gruporefuerzonivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('DOCENTE', 'Docente'), ('ADMINISTRADOR', 'Administrador')], max_length=20),
        ),
    ]
