# Generated by Django 5.2.6 on 2025-10-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LevelUp', '0005_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemactividad',
            name='tipo',
            field=models.CharField(choices=[('mcq', 'Opción múltiple'), ('tf', 'Verdadero/Falso'), ('fib', 'Completar espacios'), ('sort', 'Ordenar'), ('match', 'Emparejar'), ('text', 'Respuesta de texto'), ('image', 'Pregunta con imagen'), ('interactive', 'Interactiva (embed/url)'), ('game', 'Juego (embed)')], max_length=20),
        ),
    ]
