# Generated by Django 5.2.6 on 2025-10-09 03:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LevelUp', '0006_alter_itemactividad_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='intentos_max',
            field=models.PositiveSmallIntegerField(default=1, help_text='Número máximo de intentos por estudiante (1–20).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='submission',
            name='intento',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
