# Generated by Django 5.2.6 on 2025-10-09 03:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LevelUp', '0007_actividad_intentos_max_submission_intento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-intento', '-id']},
        ),
        migrations.AddField(
            model_name='asignacionactividad',
            name='intentos_permitidos',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Si se define, reemplaza los intentos máximos de la actividad para este estudiante.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('actividad', 'estudiante', 'intento')},
        ),
    ]
