# Generated by Django 5.2.7 on 2025-10-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LevelUp', '0008_alter_submission_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='nivel',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='accesorios_desbloqueados',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='accesorios_equipados',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='avatar_kind',
            field=models.CharField(default='otter', max_length=20),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='avatar_slug',
            field=models.CharField(default='otter', max_length=40),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='habilidades',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
