# Generated by Django 5.2.6 on 2025-10-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LevelUp', '0009_remove_estudiante_nivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
    ]
