# Generated by Django 5.2.7 on 2025-10-18 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LevelUp', '0010_estudiante_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='LevelUp.asignatura'),
        ),
    ]
