# Generated by Django 5.2.7 on 2025-10-18 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LevelUp', '0011_actividad_asignatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='LevelUp.asignatura'),
        ),
    ]
