# Generated by Django 5.2.6 on 2025-10-18 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LevelUp', '0012_alter_actividad_asignatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruporefuerzonivel',
            name='profesor_ciencias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_refuerzo_cien', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gruporefuerzonivel',
            name='profesor_historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_refuerzo_hist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gruporefuerzonivel',
            name='profesor_lenguaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_refuerzo_leng', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.IntegerField(choices=[(4, '4° Básico'), (5, '5° Básico'), (6, '6° Básico'), (7, '7° Básico'), (8, '8° Básico')]),
        ),
        migrations.AlterField(
            model_name='gruporefuerzonivel',
            name='nivel',
            field=models.IntegerField(choices=[(4, '4° Básico'), (5, '5° Básico'), (6, '6° Básico'), (7, '7° Básico'), (8, '8° Básico')], unique=True),
        ),
    ]
