# Generated by Django 5.2.6 on 2025-10-24 00:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LevelUp', '0013_gruporefuerzonivel_profesor_ciencias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='intentos_max',
            field=models.PositiveSmallIntegerField(default=1, help_text='Número máximo de intentos por estudiante (1–1000).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('DOCENTE', 'Docente'), ('ADMINISTRADOR', 'Administrador')], default='ESTUDIANTE', max_length=20),
        ),
    ]
