# Generated by Django 5.2.6 on 2025-10-24 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LevelUp', '0014_alter_actividad_intentos_max_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='actividad',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='LevelUp.asignatura'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('juego', 'Juego')], max_length=20),
        ),
    ]
