# Generated by Django 5.2.6 on 2025-11-01 16:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LevelUp', '0015_alter_actividad_options_alter_actividad_asignatura_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionactividad',
            options={'ordering': ['-fecha_asignacion', 'actividad_id']},
        ),
        migrations.AlterModelOptions(
            name='reporteprogreso',
            options={'ordering': ['-fecha', 'id']},
        ),
        migrations.AlterField(
            model_name='reporteprogreso',
            name='avance',
            field=models.FloatField(help_text='Porcentaje 0–100'),
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Pregunta')),
                ('opciones', models.JSONField(default=list, help_text='Lista de 2 a 6 opciones (en orden)', verbose_name='Opciones')),
                ('correcta', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Índice de la respuesta correcta (0-based)')),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Medio'), ('dificil', 'Difícil')], default='medio', max_length=10)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('activa', models.BooleanField(default=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='LevelUp.actividad')),
            ],
            options={
                'ordering': ['orden', 'id'],
                'unique_together': {('actividad', 'orden')},
            },
        ),
    ]
