# Generated by Django 5.2.6 on 2025-11-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LevelUp', '0016_alter_asignacionactividad_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='dificultad_default',
            field=models.CharField(choices=[('FACIL', 'Fácil'), ('MEDIO', 'Medio'), ('DIFICIL', 'Difícil')], default='MEDIO', max_length=16),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='dificultad',
            field=models.CharField(choices=[('FACIL', 'Fácil'), ('MEDIO', 'Medio'), ('DIFICIL', 'Difícil')], default='MEDIO', max_length=16),
        ),
    ]
