# Generated by Django 5.2.6 on 2025-11-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LevelUp', '0017_actividad_dificultad_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemactividad',
            name='enunciado',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemactividad',
            name='tipo',
            field=models.CharField(choices=[('mcq', 'Opción múltiple'), ('tf', 'Verdadero/Falso'), ('fib', 'Completar espacios'), ('sort', 'Ordenar'), ('match', 'Emparejar'), ('text', 'Respuesta de texto'), ('image', 'Pregunta con imagen'), ('interactive', 'Interactiva (embed/url)'), ('game', 'Juego (embed)'), ('game_config', 'Juego • Configuración')], max_length=20),
        ),
    ]
