# Generated by Django 5.2.6 on 2025-11-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LevelUp', '0018_alter_itemactividad_enunciado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignatura',
            options={},
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='codigo',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='icono',
            field=models.CharField(blank=True, help_text="Ej: 'LevelUp/img/asignaturas/matematicas.png'", max_length=200, verbose_name='Icono (ruta static)'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
