# Generated by Django 5.2.6 on 2025-11-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LevelUp', '0019_alter_asignatura_options_remove_asignatura_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='intentos_ilimitados',
            field=models.BooleanField(default=False, help_text='Si está activo, el estudiante puede intentarlo sin límite.'),
        ),
    ]
