# Generated by Django 5.2.7 on 2025-11-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LevelUp', '0020_actividad_intentos_ilimitados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('game', 'Minijuego')], max_length=20),
        ),
    ]
