# Generated by Django 5.2.6 on 2025-11-27 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LevelUp', '0021_alter_actividad_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='recompensa',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='recurso',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='accesorios_desbloqueados',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='accesorios_equipados',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='avatar_kind',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='avatar_slug',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='habilidades',
        ),
        migrations.RemoveField(
            model_name='itemactividad',
            name='imagen',
        ),
    ]
