# Generated by Django 5.2.6 on 2025-11-19 17:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('condicion_texto', models.CharField(blank=True, max_length=255)),
                ('icono', models.CharField(blank=True, help_text="Ruta estática opcional, ej: 'LevelUp/img/recompensas/medalla_math.png'", max_length=255)),
                ('tipo', models.CharField(choices=[('LOGRO', 'Logro'), ('FONDO', 'Fondo de pantalla'), ('ACCESORIO', 'Accesorio de avatar'), ('OTRO', 'Otro')], default='LOGRO', max_length=20)),
                ('nivel_requerido', models.PositiveIntegerField(default=0)),
                ('xp_requerida', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Recompensa',
                'verbose_name_plural': 'Recompensas',
            },
        ),
        migrations.CreateModel(
            name='PerfilGamificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveIntegerField(default=0)),
                ('xp_actual', models.PositiveIntegerField(default=0)),
                ('xp_total', models.PositiveIntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_gamificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de gamificación',
                'verbose_name_plural': 'Perfiles de gamificación',
            },
        ),
        migrations.CreateModel(
            name='RecompensaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desbloqueo', models.DateTimeField(default=django.utils.timezone.now)),
                ('notificada', models.BooleanField(default=False)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recompensas_usuario', to='gamificacion.perfilgamificacion')),
                ('recompensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_con_recompensa', to='gamificacion.recompensa')),
            ],
            options={
                'verbose_name': 'Recompensa de usuario',
                'verbose_name_plural': 'Recompensas de usuarios',
                'unique_together': {('perfil', 'recompensa')},
            },
        ),
    ]
