# Generated by Django 5.2.6 on 2025-11-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilgamificacion',
            name='actividades_completadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recompensa',
            name='actividades_requeridas',
            field=models.PositiveIntegerField(default=0, help_text='Número de actividades completadas necesarias.'),
        ),
    ]
