# Generated by Django 5.2.6 on 2025-11-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacion', '0002_perfilgamificacion_actividades_completadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recompensa',
            name='actividades_requeridas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
